SELECT A.NAME as "name",
       round(A.OMEGA*(1.618),3) AS "Fator N"
  FROM LIFE_REGISTRY A
  LEFT JOIN DIMENSIONS B ON B.ID = DIMENSIONS_ID
  WHERE UPPER(A.NAME) LIKE 'RICHAR%'
    AND B.NAME IN('C875','C774')
 ORDER BY 2 ASC